apiVersion: apps/v1
kind: Deployment
metadata:
  name: learninggcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: varun
        image: nginx:1.14.2
        ports:
        - containerPort: 80
